name: Farset Labs
description: "Northern Ireland's Hackerspace"
tags: "hackerspace, makerspace, belfast, technology, maker movement"
markdown: kramdown
exclude: [README.md, _scripts, Gemfile, Gemfile.lock, etc, bin, makefile, buildout.cfg, bootstrap.py, requirements.txt]
plugins_dir: ./_plugins
base: ""
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
paginate_path: "news/page:num"
paginate: 5
url: "http://www.farsetlabs.org.uk"
social:
  github: FarsetLabs
  facebook: FarsetLabs
  gplus: FarsetLabsOrgUk
  twitter: FarsetLabs
  flickr: groups/farset_labs
  blogfeed: "http://blog.farsetlabs.org.uk/feed/"
  forum: "http://discourse.farsetlabs.org.uk/"
links:
  - name: Blog
    url: "http://blog.farsetlabs.org.uk/"
  - name: Social
    url: ""
    list:
    - name: Facebook
      url: "http://facebook.com/FarsetLabs"
    - name: Twitter
      url: "http://twitter.com/FarsetLabs"
    - name: Forum
      url: "http://discourse.farsetlabs.org.uk/"
    - name: Flickr
      url: "http://www.flickr.com/groups/farset_labs"
    - name: Wiki
      url: "http://wiki.farsetlabs.org.uk/"
officers:
  - name: Andrew Bolster
    username: bolster
    year: 2011 -
    title: "Director/Founder"
    blurb: "Autonomous Systems Researcher, Consultant, Speaker, and Enfant Terrible. You can see some of his work over on [his website](http://andrewbolster.info)"
    email: "bolster@farsetlabs.org.uk"
    twitter: "bolster"
    website: "http://andrewbolster.info"
    facebook: "andrewbolster"
    linkedin: "andrewbolster"
    github: "andrewbolster"
    discourse: "bolster"

  - name: David Kane
    username: kane
    year: 2011 -
    title: "Director/Founder"
    blurb: "Postgraduate researcher specialising in condensed matter physics, embedded developer and all round good guy."
    email: "david@farsetlabs.org.uk"
    twitter: "dsrkane"
    discourse: "kane"

  - name: Dylan Wylie
    username: wylie
    year: 2013 -
    title: "Director"
    blurb: "Co-founder of rapidly growing health consultancy startup,  [We Slim Together](http://www.weslimtogether.co.uk), physicist, developer & technologist."
    email: "dylan@farsetlabs.org.uk"
    twitter: "dylwylie"
    discourse: "dylan"

  - name: Colin Mitchell
    username: pixelpage
    year: 2016 -
    title: "Director"
    blurb: "Business Technology Advisor, interim CTO & troubleshooter/causer, hands-on code-tweaker, occasional blues guitarist"
    email: "colin.mitchell@farsetlabs.org.uk"
    twitter: "pixelpage"
    linkedin: "colinmitch"

  - name: Daniel Porter
    username: porter
    year: 2014 -
    title: "Digital Infrastructure NEM"
    email: "digitalinfrastructure@farsetlabs.org.uk"
    discourse: "stealthii"
    blurb: "Daniel makes the bits go around"
    twitter: "stealthii"
    github: "stealthii"

  - name: Glenn Davidson
    username: davidson
    year: 2014 -
    title: "Events NEM"
    blurb: "Glenn is an enthusiastic software engineer with 10 years experience in business problem analysis, enterprise systems, and mobile technology.  While currently working on cutting-edge start-up and mobile projects as part of [Coding Fury Ltd](http://www.codingfury.com/), he also organises local events for Ireland's independent game industry. Glenn is the central point of contact for Farsets event scheduling and logistics"
    email: "events@farsetlabs.org.uk"
    discourse: "panloaf"
    twitter: "glenndavidson"
    facebook: "panloaf"
    website: "http://blitter.co.uk"
    linkedin: "glennrdavidson"

  - name: Colin Kelsey
    username: kelsey
    year: 2015 -
    title: "Project Room NEM"
    blurb: "Research scientist with a PhD in Plasma Physics and a particular interest in medical applications.  Also homebrewer, DIY enthusiast and general hands-on person for building or fixing anything in the workshop that needs built or fixed."
    email: "projects@farsetlabs.org.uk"
    linkedin: "colinkelsey"
    facebook: "colin.kelsey"
    discourse: "colin"

  - name: Claire Wilgar
    username: wilgar
    year: 2015 -
    title: "Community NEM"
    blurb: "Claire is a senior frontend developer and organiser of Girl Geeks Belfast and co-organiser of Global Game Jam and BelfastJS, and is the point of contact for member and community issues and queries in Farset Labs."
    email: "community@farsetlabs.org.uk"
    discourse: "clairebones"
    twitter: "clairedotw"

  - name: Andrew Mulholland
    username: mulholland
    year: 2015 -
    title: "Outreach NEM"
    email: "outreach@farsetlabs.org.uk"
    blurb: "Award winning Inventor, Raspberry Pi expert, Computer Science teacher, STEMNET Ambassador, UK TalkTalk Digital Hero 2014 and @PiNetDev developer."
    discourse: "gbaman1"
    twitter: "gbaman1"
    website: "http://pi.gbaman.info/"

