title: Farset Labs
description: "Northern Ireland's Hackerspace"
tags: "hackerspace, makerspace, belfast, technology, maker movement"
markdown: kramdown
exclude: [README.md, _scripts, Gemfile, Gemfile.lock, etc, bin, makefile, buildout.cfg, bootstrap.py, requirements.txt]
plugins_dir: ./_plugins
repository: FarsetLabs/farsetlabs.github.io
base: ""
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
paginate_path: "news/page:num"
paginate: 5
url: "https://www.farsetlabs.org.uk"
social:
  github: "https://www.github.com/FarsetLabs"
  facebook: "https://www.facebook.com/FarsetLabs"
  twitter: "https://www.twitter.com/FarsetLabs"
  flickr: "https://www.flickr.com/groups/farset_labs"
  twitch: "https://www.twitch.tv/farsetlabs"
  instagram: "https://www.instagram.com/farsetlabs"
  linkedin: "https://uk.linkedin.com/company/farset-labs"
membership_tiers:
  monthly:
    - name: Casual
      description: For students and those who are occasionally in the space.
      benefits:
        - ğŸª 24/7 access
        - ğŸ¤– Fair use of workshop facilities (training may be required)
        - ğŸŸï¸ Free entry to Farset Labs events
      url: "https://farsetlabs.spaces.nexudus.com/signup?tariff_guid=2bbe61f6-f61c-43ae-955b-447d3f5694a4"
      price: 20
    - name: Standard
      description: For those who regularly use the space.
      benefits:
        - ğŸª 24/7 access
        - ğŸ¤– Fair use of workshop facilities (training may be required)
        - ğŸŸï¸ Free entry to Farset Labs events
      url: "https://farsetlabs.spaces.nexudus.com/signup?tariff_guid=19b169ca-f352-46fb-9b6c-d7c0c5b00385"
      price: 35
    - name: Professional
      description: For those consistently in the space with ongoing long term projects.
      benefits:
        - ğŸª 24/7 access
        - ğŸ¤– Fair use of workshop facilities (training may be required)
        - ğŸŸï¸ Free entry to Farset Labs events
      url: "https://farsetlabs.spaces.nexudus.com/signup?tariff_guid=ec3a5718-ab0d-4814-b276-9a637b0e9468"
      price: 50
    # casual: "https://farsetlabs.spaces.nexudus.com/signup?tariff_guid=2bbe61f6-f61c-43ae-955b-447d3f5694a4"
    # standard: "https://farsetlabs.spaces.nexudus.com/signup?tariff_guid=19b169ca-f352-46fb-9b6c-d7c0c5b00385"
    # professional: "https://farsetlabs.spaces.nexudus.com/signup?tariff_guid=ec3a5718-ab0d-4814-b276-9a637b0e9468"
officers:
  - name: Colin Mitchell, Secretary
    pronouns: "he/him"
    username: pixelpage
    year: 2016 -
    title: "Director"
    blurb: "Business Technology Advisor, interim CTO & troubleshooter/causer, hands-on code-tweaker, occasional blues guitarist."
    email: "colin.mitchell@farsetlabs.org.uk"
    twitter: "pixelpage"
    linkedin: "colinmitch"

  - name: Artemiy Kondratiev, Chair
    pronouns: "he/him"
    username: art
    year: 2018 -
    title: "Director"
    blurb: "Software engineer, public speaker and event organiser."
    email: "art@farsetlabs.org.uk"
    twitter: "awflwafl"
    linkedin: "artemiy-kondratiev"
    github: "awflwafl"
